### ISSUE TITLE
WR display for each round in Fallalytics.

### ISSUE THREAD

**Issue by qubqub** [Hoier/Fallalytics#3]
@Hoier Recently, I've had some friends comment that it would be nice to have a page in Fallalytics where you could see the WR for each round of a race, for example, where you could see the fastest time for a round of a race. In FallguysStats, you could just add the time for the round and send it in, and in Fallalytics, you could update it whenever there was a faster time.

I'm curious to know what your thoughts are on this.

**Comment by Hoier** [comment]
@qutrits This is a great feature request. Im currently reworking the design of the page, to make it easier to display more stats about spessific rounds. There currently is not a WR included in the "single round template" but it should be super easy to add. Ill keep this issue open, so you can track progress 👍

**Comment by qubqub** [comment]
FallGuysStats can also send the user's Steam or Epic Games nickname and a record of the race round.
and since the user's nickname may change, I think it's a good idea to send the user's Steam or Epic Games ID as well.

@Hoier What do you think of the comments below?
1. Display icons for Epic Games and Steam for each nickname(ID)
2. Show up to 1000th place for each level(round)
3. Display gold medals for first place, silver medals for the top 20%, bronze medals for the top 50%, and pink medals for all other participants
4. Show rankings in the middle of the medals from 1st to 3rd
5. If the rankings are tied, the person with the earliest record date is shown as the higher ranked (This requires sending an additional Finish Date)

@Hoier I'd love to hear your thoughts on any of the above.
If it is difficult to proceed, I plan to develop and operate a web page myself.

**Comment by Hoier** [comment]
@qutrits I love the ideas. Im 90% done with the rework on fallalytics, and can definitly include the leaderboard for each round soon. I would love to have a chat with you on discord and show you what the current plans are. Sending you an email 👍
